# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            'Open NFT Bot Awesome'
tagline:          'Open NFT Bot Awesome'
description:      'Awesome-NFT Awesome list of awesome Non Fungible Token (NFT, ERC721, ERC1155) frameworks, libraries and software resources.'
url:              http://opennftbot.com/
baseurl:          /

author:
  name:           ''
  url:            https://twitter.com/opennftbot

paginate:         5

# Custom vars
version:          1.2.0

github:
  repo:           https://github.com/opennftbot
